In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])
a.ndim

1

In [3]:
a=np.array([[1,2,3,4,5,6]])
a.ndim

2

In [7]:
b=np.array([1,2,3,4,5,6]).reshape(1,-1)
b.ndim

2

In [10]:
a=np.array([[1,2,3,4,5,6]]).flatten()
a.ndim

1

In [16]:
c=np.logspace(1,10)
c

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

In [15]:
c.ndim

1

In [18]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [21]:
np.arange(1,4,3)

array([1])

In [24]:
from scipy import linalg

In [29]:
a=np.array([1,2,3,4,5,6])
b=np.array([2,3,5,4,3,6])

In [34]:
np.linalg.norm(a-b,0)

4.0

In [35]:
from scipy import stats

In [37]:
from scipy.spatial.distance import euclidean

In [38]:
euclidean(a,b)

3.1622776601683795

In [41]:
stats.zscore(a)

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [49]:
a=np.array([1,2])
b=np.array([2,3])
round(np.linalg.norm(a-b),2)

1.41

In [51]:
a=0.4567
a*100

45.67

In [75]:
round(a*100,2)

45.67

In [58]:
round(15.57)

16

In [61]:
import math

In [73]:
math.floor(16.0)

16

In [102]:
import matplotlib.pyplot as plt

In [103]:
import pandas as pd

In [130]:
dataset={"k":[[1,2],[2,3],[3,1]],"r":[[6,5],[7,7],[8,6]]}
dataset

{'k': [[1, 2], [2, 3], [3, 1]], 'r': [[6, 5], [7, 7], [8, 6]]}

In [131]:
row_feature=[5,6]

In [132]:
[(plt.scatter(ii[0],ii[1],s=100,color=i) for ii in dataset[i]) for i in dataset]

[<generator object <listcomp>.<genexpr> at 0x0000017E996823B8>,
 <generator object <listcomp>.<genexpr> at 0x0000017E99682410>]

In [133]:
plt.show()